#!/usr/bin/env ruby

# Switch branches and merge in master
`git co gh-pages; git merge master;`

# Generate manifest
lines = []
lines << 'CACHE MANIFEST'
lines << "# Version: "+ `git show master`.split("\n").first.gsub(/^commit\s/, '')
Dir.entries('.').each do |name|
  next if name =~ /^\./
  next if name =~ /\.coffee$/
  next if name == 'deploy'
  puts name
  lines << name
end
File.open('mandalatron.appcache', 'w+') do |f|
  f.write lines.join("\n")
end

# Commit app cache
`git commit -a -m 'appcache update'`

# Push
`git push`

# Switch back to master
`git co master`